### ISSUE TITLE
RPC call "zcash-cli getblocksubsidy" does not return results

### ISSUE THREAD

**Issue by num81** [bitcoinzero/bitcoinzero#1]
The getblocksubsidy call is used for z-nomp pools ans is not returning a result, causing the pool connection to fail to the deamon.

BitcoinZero response
zen@pool:~/bitcoinzero/bitcoinzero$ ./src/zcash-cli getblocksubsidy
error code: -32601
error message:
Method not found

Zencash response
zen@pool:~/bitcoinzero/bitcoinzero$ zen-cli getblocksubsidy
{
  "miner": 11.00000000,
  "community": 1.50000000
}

Bitcoinz response
zen@pool:~/bitcoinzero/bitcoinzero$ zcash-cli getblocksubsidy
{
  "miner": 12500.00000000,
  "founders": 0.00000000
}

**Comment by yushizhao** [comment]
Yes. Bitcoin Zero does not support this RPC, yet. 
And it uses a different PoW method from Zencash or Bitcoinz or Zcash. Bitcoin Zero uses Merged Mining like namecoin and dogecoin. I have updated the README.md with a "How To Mine" section you may found helpful.

**Comment by yushizhao** [comment]
I have added this RPC.
~/bitcoinzero$ ./src/zcash-cli getblocksubsidy
{
  "miner": 2.50000000,
  "founders": 0.62500000
}

**Comment by num81** [comment]
Thank you,  This does allow the pool to connect to the daemon now.

I will start looking at the change to the PoW method now.

**Comment by yushizhao** [comment]
You are welcome. 
I will take further questions on interacting within NOMP here.

**Comment by num81** [comment]
A couple of questions;

What value is the getnetworkhashps function displaying?

bitcoinzero@bitcoinzero:~$ zcash-cli getnetworkhashps
2372593799980051968

Is that 2.3 Petahash?  That doesn't seem correct.

![image](https://user-images.githubusercontent.com/9110495/35493505-0eadaab6-0508-11e8-8a34-c2d4b92b933c.png)

What is the correct current network speed and difficulty?

**Comment by yushizhao** [comment]
@num81 I have not changed this part of code. And I compare the GetNetworkHashPS RPC with Bitcoin's just now. They are doing the same thing. 
So, probably, this is the correct value.
What makes you think it should be some other value?

**Comment by num81** [comment]
@yushizhao here as some examples of the output of other Equihash coins;

Zen
zen@pool:~$ zen-cli getnetworkhashps
37304489

37.3 MSol/s

Bitcoinz 
zen@pool:~$  zcash-cli getnetworkhashps
7887145

7.89 MSol/s

Snowgem
snowgem@snowgem:~$ snowgem-cli getnetworkhashps
722596

722 KSol/s

Bitcoinzero
bitcoinzero@bitcoinzero:~$ zcash-cli getnetworkhashps
1803053246841628160

1.8 PSol/s

You may need to compare the value in some of the source codes for other equihash coins as something seems a bit off.

**Comment by yushizhao** [comment]
I see you point. Well, try not compare with other equihash coins, because Bitcoin Zero uses a different mining method. 
To be more specific, it is not equihash, but Merged Mining with Bitcoin.

**Comment by num81** [comment]
that will be the problem then, I was under the impression that it was an Equihash minealbe coin.

**Comment by yushizhao** [comment]
I assume there are no further questions here. Well, feel free to start a new issue.
